#coding=utf-8

python_buildin_function = ['abs', 'delattr', 'hash', 'memoryview', 'set', 'all', 'dict', 'help', 'min', 'setattr',
                       'any', 'dir', 'hex', 'next', 'slice', 'ascii', 'divmod', 'id', 'object', 'sorted', 'bin',
                       'enumerate', 'input', 'oct', 'staticmethod', 'bool', 'eval', 'int', 'open', 'str',
                       'breakpoint', 'exec', 'isinstance', 'ord', 'sum', 'bytearray', 'filter', 'issubclass', 'pow',
                       'super', 'bytes', 'float', 'iter', 'print', 'tuple', 'callable', 'format', 'len', 'property',
                       'type', 'chr', 'frozenset', 'list', 'range', 'vars', 'classmethod', 'getattr', 'locals', 'repr',
                       'zip', 'compile', 'globals', 'map', 'reversed', '__import__', 'complex', 'hasattr', 'max',
                       'round', 'lambda']

cpp_keywords = ['auto', 'const', 'double', 'float', 'int', 'short', 'struct', 'unsigned', 'break', 'continue', 'else',
                'for', 'long', 'signed', 'switch', 'void', 'case', 'default', 'enum', 'goto', 'register', 'sizeof',
                'typedef', 'volatile', 'char', 'do', 'extern', 'if', 'return', 'static', 'union', 'while', 'asm',
                'dynamic_cast', 'namespace', 'reinterpret_cast', 'try', 'bool', 'explicit', 'new', 'static_cast',
                'typeid', 'catch', 'false', 'operator', 'template', 'typename', 'class', 'friend', 'private', 'this',
                'using', 'const_cast', 'inline', 'public', 'throw', 'virtual', 'delete', 'mutable', 'protected', 'true',
                'wchar_t', 'and', 'bitand', 'compl', 'not_eq', 'or_eq', 'xor_eq', 'and_eq', 'bitor', 'not', 'or', 'xor',
                'cin', 'endl', 'INT_MIN', 'iomanip', 'main', 'npos', 'std', 'cout', 'include', 'INT_MAX', 'iostream',
                'MAX_RAND', 'NULL', 'string', 'alignas', 'alignof', 'atomic_cancel', 'atomic_commit', 'atomic_noexcept',
                'char16_t', 'char32_t', 'concept', 'constexpr', 'co_await', 'co_return', 'co_yield', 'decltype',
                'export', 'noexcept', 'nullptr', 'reflexpr', 'requires', 'static_assert', 'synchronized', 'thread_local',
                'override', 'final', 'audit', 'axiom', 'transaction_safe', 'transaction_safe_dynamic']

cpp_buildin_function = ['bitset', 'vector', 'container', 'map', 'multimap', 'fin', 'fout', 'priority_queue', 'queue',
                        'stack', 'string', 'accumulate', 'adjacent_difference', 'adjacent_find', 'any', 'append',
                        'assign', 'at', 'auto_ptr', 'back', 'bad', 'begin', 'binary_search', 'c_str', 'capacity',
                        'clear', 'close', 'compare', 'copy', 'copy_backward', 'copy_n', 'count', 'count_if', 'data',
                        'empty', 'end', 'eof', 'equal', 'equal_range', 'erase', 'fail', 'fill', 'fill_n', 'find',
                        'find_end', 'find_first_not_of', 'find_first_of', 'find_if', 'find_last_not_of', 'find_last_of',
                        'flags', 'flip', 'flush', 'for_each', 'front', 'gcount', 'generate', 'generate_n', 'get',
                        'getline', 'good', 'ignore', 'includes', 'inner_product', 'inplace_merge', 'insert', 'is_heap',
                        'is_sorted', 'iter_swap', 'key_comp', 'length', 'lexicographical_compare', 'lexicographical_compare_3way',
                        'lower_bound', 'make_heap', 'max', 'max_element', 'max_size', 'merge', 'min', 'min_element',
                        'mismatch', 'next_permutation', 'none', 'nth_element', 'open', 'partial_sort', 'partial_sort_copy',
                        'partial_sum', 'partition', 'peek', 'pop', 'pop_back', 'pop_front', 'pop_heap', 'precision',
                        'prev_permutation', 'push', 'push_back', 'push_front', 'push_heap', 'put', 'putback',
                        'random_sample', 'random_sample_n', 'random_shuffle', 'rbegin', 'rdstate', 'read', 'remove',
                        'remove_copy', 'remove_copy_if', 'remove_if', 'rend', 'replace', 'replace_copy', 'replace_copy_if',
                        'replace_if', 'reserve', 'reset', 'resize', 'reverse', 'reverse_copy', 'rfind', 'rotate',
                        'rotate_copy', 'search', 'search_n', 'seekg', 'seekp', 'set', 'set_difference', 'set_intersection',
                        'set_symmetric_difference', 'set_union', 'setf', 'size', 'sort', 'sort_heap', 'splice',
                        'stable_partition', 'stable_sort', 'substr', 'swap', 'swap_ranges', 'sync_with_stdio',
                        'tellg', 'tellp', 'test', 'to_string', 'to_ulong', 'top', 'transform', 'unique', 'unique_copy',
                        'unsetf', 'upper_bound', 'value_comp', 'width', 'write']