# Generated by Django 2.1 on 2018-10-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('father_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Label', verbose_name='父节点')),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_sample', models.TextField(blank=True, null=True)),
                ('output_sample', models.TextField(blank=True, null=True)),
                ('testcase_folder', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=3000)),
                ('memory_limit', models.IntegerField(default=65536)),
                ('spare', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.ManyToManyField(blank=True, to='search.Label', verbose_name='标签')),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='ProblemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Language')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Problem')),
            ],
            options={
                'db_table': 'problemCode',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_code', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_code', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('spare', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
